sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    # password: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0 # 要使用的储存库 0-15
  wechat:
    appid: wxaffe41c5ea7a098
    secret: 2508bbdc42af80b47284979cd06f93a
